[build]
  base = "reactp10"          
  publish = "dist"           
  command = "npm run build"
  functions = "netlify/functions"  

[dev]
  functions = "netlify/functions"
  envFiles = [".env", ".env.functions"]
